---
- name: Setup technical user with SSH key and sudo rights
  hosts: all
  become: yes
  vars:
    tech_user: techuser  # Имя технического пользователя
    tech_user_ssh_key: "ssh-rsa AAAA..."  # Публичный SSH-ключ
    tech_user_sudo: true  # Выдавать ли права sudo

  tasks:
    - name: Ensure technical user exists
      ansible.builtin.user:
        name: "{{ tech_user }}"
        state: present
        shell: /bin/bash
        create_home: yes
        home: "/home/{{ tech_user }}"

    - name: Ensure .ssh directory exists for {{ tech_user }}
      ansible.builtin.file:
        path: "/home/{{ tech_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ tech_user }}"
        group: "{{ tech_user }}"

    - name: Add SSH key for {{ tech_user }}
      ansible.builtin.lineinfile:
        path: "/home/{{ tech_user }}/.ssh/authorized_keys"
        line: "{{ tech_user_ssh_key }}"
        create: yes
        mode: '0600'
        owner: "{{ tech_user }}"
        group: "{{ tech_user }}"

    - name: Ensure {{ tech_user }} has sudo rights
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ tech_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
      when: tech_user_sudo
